from enum import Enum

TABLES = {
"TB_EVENT_TYPE": """
    CREATE TABLE TB_EVENT_TYPE(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL
    );
""",
"TB_GUILD": """
CREATE TABLE TB_GUILD(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL
);
""",
"TB_USER":"""
CREATE TABLE TB_USER(
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL,
    FL_BOT INTEGER
);
""",

"TB_EVENTS":"""
CREATE TABLE TB_EVENTS(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ID_USER INTEGER NOT NULL,
    ID_GUILD INTEGER NOT NULL,
    ID_EVENT_TYPE INTEGER NOT NULL,
    DS_EVENT TEXT,
    DH_EVENT TEXT NOT NULL
);
"""
}

class EVENT_TYPES(Enum):
    JOIN = 1
    LEAVE = 2
    KICK = 3
    BAN = 4
    ONLINE = 5
    OFFLINE = 6
    IDLE = 7
    DND = 8
    NICK_CHANGE = 9
    VOICE_CONNECT = 10
    VOICE_DISCONNECT = 11
    VOICE_MUTE_START = 12
    VOICE_MUTE_STOP = 13
    VOICE_DEAF_START = 14
    VOICE_DEAF_STOP = 15
    STREAM_START = 16
    STREAM_STOP = 17
    PLAYING_START = 18
    PLAYING_STOP = 19
    MESSAGE_SEND = 20
    MESSAGE_EDIT = 21
    MESSAGE_DELETE = 22
    UNBAN = 23
    VOICE_AFK_START = 24
    VOICE_AFK_STOP = 25
    VOICE_MOVE = 26
    VOICE_GUILD_MUTE_START = 27
    VOICE_GUILD_MUTE_STOP = 28
    VOICE_GUILD_DEAF_START = 29
    VOICE_GUILD_DEAF_STOP = 30
    PLAYING_CHANGE = 31
    MUSIC_PLAY = 32